strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - tests
  - build
  - env
  - resources
  - flamapy/metamodels/fm_metamodel/transformations/uvl_parser/UVLLexer.py
  - flamapy/metamodels/fm_metamodel/transformations/uvl_parser/UVLListener.py
  - flamapy/metamodels/fm_metamodel/transformations/uvl_parser/UVLParser.py
  - .mypy_cache

pycodestyle:
  options:
    max-line-length: 100

pylint:
  disable:
    - super-init-not-called
    - unsubscriptable-object

mccabe:
  run: true
